**Problem 1** Reduced Row Echelon Form and Rank

In [4]:
import numpy as np
A = np.array([[1., 2., 2., 1.], [4., 8., 9., 3.], [0., 3., 2., 1.]])
B = np.array([[1., 2., 3.], [2. ,4., 6. ], [1., 4., 8.]])



**1.1** Row echelon form by Gaussian elimination

In [6]:
def checkAllZero(list1, val):
    for x in list1:
        if np.abs(x) > val:
            return False
    return True
    
def ref(A, eps=1e-10):
  R = A.copy()
  num_row = R.shape[0]
  num_col = R.shape[1]
  row_idx = 0
  pvt_idx = 0
  pvt_idx_list = []
  ################Your code starts here#########################
  while (row_idx < num_row and pvt_idx < num_col):
    temp = [R[i][pvt_idx] for i in range(row_idx,num_row)]
    if checkAllZero(temp, eps):
      pvt_idx += 1
      continue
    if np.abs(R[row_idx][pvt_idx]) <= eps:
      temp2 = [R[j][pvt_idx] for j in range(row_idx,num_row)]
      nonzero_idx = np.argmax(temp2) # - eps)
      R[row_idx][:] = R[row_idx + nonzero_idx][:]
    for r in range(row_idx + 1, num_row):
      multiplier = np.multiply(-1,R[r][pvt_idx])/R[row_idx][pvt_idx]
      R[r][:] += np.multiply(multiplier, R[row_idx][:])
    pvt_idx_list.append(pvt_idx)
    pvt_idx += 1
    row_idx += 1
  ###############################################################
  return R, pvt_idx_list

In [7]:
R, pvt_idx_list = ref(A)
# print out the row echelon form
print("row echelon form of A:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

row echelon form of A:
[[1. 2. 2. 1.]
 [0. 3. 2. 1.]
 [0. 0. 0. 0.]]
Indices of pivot values:
[0, 1]


In [8]:
R, pvt_idx_list = ref(B)
# print out the row echelon form
print("row echelon form of B:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

row echelon form of B:
[[1. 2. 3.]
 [0. 2. 5.]
 [0. 0. 0.]]
Indices of pivot values:
[0, 1]


**1.2** Reduced row echelon form by Gauss-Jordan elimination

In [9]:
def rref(A):
  R, pvt_idx_list = ref(A)
  num_row = R.shape[0]
  num_col = R.shape[1]
  #####################Your code starts here#######################
  for row_idx, pvt_idx in enumerate(pvt_idx_list):
    for i in range(0, row_idx):
      multiplier = np.multiply(-1,R[i][pvt_idx])/R[row_idx][pvt_idx]
      R[i][:] += np.multiply(multiplier, R[row_idx][:])
  for row_idx, pvt_idx in enumerate(pvt_idx_list):
    R[row_idx][:] = np.divide(R[row_idx][:],R[row_idx][pvt_idx])
  ###################################################################
  return R
         

In [10]:
R = rref(A)
# print out the row echelon form
print("reduced row echelon form of A:")
print(R)


reduced row echelon form of A:
[[1.         0.         0.66666667 0.33333333]
 [0.         1.         0.66666667 0.33333333]
 [0.         0.         0.         0.        ]]


In [11]:
R = rref(B)
# print out the row echelon form
print("reduced row echelon form of B:")
print(R)

reduced row echelon form of B:
[[ 1.   0.  -2. ]
 [ 0.   1.   2.5]
 [ 0.   0.   0. ]]


In [12]:
# A larger matrix to test the reduced row echelon form algorithm.
C = np.array([[1., 2., 0., 2., 4., 6.], 
              [1., 2., 0., 3., 6., 9.], 
              [0., 0., 0., 1., 2., 3.], 
              [0., 0., 0., 2., 4., 5.]])

R = rref(C)
# print out the row echelon form
print("reduced row echelon form of C:")
print(R)


reduced row echelon form of C:
[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: RuntimeWarning: divide by zero encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in multiply
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


**1.3** Matrix rank and number of pivots

In [39]:
X = np.array([[1., 2., 4., 1.], [3., 6., 12., 3.], [4., 8., 16., 4.]])
Y = np.array([[1., 2., 4., 1.], [3., 6., 12., 3.], [4., 8., 16., 6.]])
Z = np.array([[1., 2., 4., 1.], [3., 5., 12., 3.], [4., 8., 16., 6.]])
# please use rref to generate the reduced row echelon form of matrices X, Y, Z
# And then check the rank and dimension of nullspace of each matrix by eyes directly
#########################Your code starts here##################################
r_X = rref(X)
r_Y = rref(Y)
r_Z = rref(Z)

print(r_X) #1
print(r_Y) #2
print(r_Z) #3

r_X_t = 1
r_Y_t = 2
r_Z_t = 3

################################################################################


[[1. 2. 4. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 2. 4. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[ 1.  0.  4.  0.]
 [-0.  1. -0. -0.]
 [ 0.  0.  0.  1.]]


In [48]:
from numpy.linalg import matrix_rank
#########Validate the answers about the matrices rank###########################
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)

print(r_X)
print(r_X)
print(r_X)

################################################################################

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


**Please double-click here and fill in the rank and dimension of nullspace of the these matrices**

rank(X) = 1, dimension of null(X) = 2 

rank(Y) = 2, dimension of null(Y) = 1

rank(Z) = 3, dimension of null(Z) = 0
